/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.gui.log;

import caja.gui.log.log4j.ConsoleAppender;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.PatternLayout;

/**
 * Panel that displays a log console
 * 
 * @author Carlos Juarez
 */
public class ConsolePanel extends javax.swing.JPanel {
    
    /**
     * Custom log4j appender
     */
    private ConsoleAppender consoleAppender;

    /**
     * Action listener performed in menu action event. This current implementation
     * cleans the console
     */
    private ActionListener menuActionListener = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            clearLogs();
        }
    };
    
    /**
     * Constructs a new instance of <code>ConsolePanel</code> class
     * The console appender is registered to the root logger
     * 
     */
    public ConsolePanel() {
        initComponents();
        String PATTERN = "[%p] %m";
        consoleAppender = new ConsoleAppender();
        consoleAppender.setLayout(new PatternLayout(PATTERN));
        consoleAppender.activateOptions();
        consoleAppender.setTextComponent(consoleTextPane);
        consoleAppender.setThreshold(Level.INFO);
        Logger.getRootLogger().addAppender(consoleAppender);
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem menuItem = new JMenuItem("Clear");
        menuItem.addActionListener(menuActionListener);
        popupMenu.add(menuItem);
        consoleTextPane.setComponentPopupMenu(popupMenu);
    }
    
    public void clearLogs(){
        consoleTextPane.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        consoleTextPane = new javax.swing.JTextPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));

        jScrollPane2.setViewportView(consoleTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane consoleTextPane;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

  
}
